#!/bin/bash -l
# Set the number of nodes
#SBATCH -N 1
# Set the number of tasks/cores per node required 
#SBATCH -n 8
# Set the walltime of the job to 1 hour (format is hh:mm:ss)
#SBATCH -t 150:00:00

# E-mail on begin (b), abort (a) and end (e) of job
#SBATCH --mail-type=ALL

# E-mail address of recipient
#SBATCH --mail-user=marion.ryan@ucd.ie

# Specifies the jobname
#SBATCH --job-name=trimomatic_paired

# Change working directory to current directory
cd $SLURM_SUBMIT_DIR

module load trimmomatic
module load jdk/1.8.0.221
export TRIMMOMATIC=/opt/software/trimmomatic/0.39/trimmomatic-0.39.jar
java -jar /opt/software/trimmomatic/0.39/trimmomatic-0.39.jar PE -phred33 /scratch/marionr/Raw_Muscle_2021/1_L_Dorsi_S41_L004_R1_001.fastq.gz /scratch/marionr/Raw_Muscle_2021/1_L_Dorsi_S41_L004_R2_001.fastq.gz /scratch/marionr/Raw_Muscle_2021/1_L_Dorsi_S41_L004_R1_001_paired.fastq /scratch/marionr/Raw_Muscle_2021/1_L_Dorsi_S41_L004_R1_001_unpaired.fastq /scratch/marionr/Raw_Muscle_2021/1_L_Dorsi_S41_L004_R2_001_paired.fastq /scratch/marionr/Raw_Muscle_2021/1_L_Dorsi_S41_L004_R2_001_unpaired.fastq ILLUMINACLIP:Adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
